spring.application.name=product_Spring_boot_project


server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=postgres
spring.datasource.password=Postgres@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true